/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aquaticsmallbusiness;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Valeria Aybar
 */

class FishOrder
{
     int number;
     String typeFish;
     boolean rewardCard;

    public FishOrder(int number, String typeFish, boolean rewardCard) {
        this.number = number;
        this.typeFish = typeFish;
        this.rewardCard = rewardCard;
    }

    @Override
    public String toString() {
        return "FishOrder{" + "number=" + number + ", typeFish=" + typeFish + ", rewardCard=" + rewardCard + '}';
    }  
}

public class AquaticsGUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public AquaticsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jTextFieldTypeFish = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jLabelFishQuest = new javax.swing.JLabel();
        jLabelNumQuest = new javax.swing.JLabel();
        jSpinnerNumFish = new javax.swing.JSpinner();
        jCheckBoxRewardsCard = new javax.swing.JCheckBox();
        jLabelimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(48,142,250);

        jLabelTitle.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabelTitle.setText("Aybar's Aquatic Store");

        jTextFieldTypeFish.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldTypeFish.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTypeFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTypeFishActionPerformed(evt);
            }
        });

        jButtonSave.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelFishQuest.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabelFishQuest.setText("What Type of Fish:  GoldFish, Betta or ClownFish?");

        jLabelNumQuest.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabelNumQuest.setText("How many Fish(s)?");

        jCheckBoxRewardsCard.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jCheckBoxRewardsCard.setText("Do you own the Rewards Card? (Check Box for yes) ");

        jLabelimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aquaticsmallbusiness/aquarium.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFishQuest)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 197, Short.MAX_VALUE)
                            .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(140, 140, 140)
                            .addComponent(jLabelimage)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSpinnerNumFish, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNumQuest))
                                .addComponent(jCheckBoxRewardsCard, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle)
                    .addComponent(jTextFieldTypeFish, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelTitle)
                .addGap(36, 36, 36)
                .addComponent(jLabelFishQuest)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTypeFish, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNumQuest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerNumFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBoxRewardsCard)
                        .addGap(8, 8, 8)
                        .addComponent(jLabelimage)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSave)
                        .addGap(95, 95, 95))))
        );

        jTextFieldTypeFish.getAccessibleContext().setAccessibleParent(jTextFieldTypeFish);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTypeFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTypeFishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTypeFishActionPerformed

    ArrayList<FishOrder> arrayList = new ArrayList<>();
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        PrintWriter pw = null;
        try {
            int num = (int)jSpinnerNumFish.getValue();
            String type = jTextFieldTypeFish.getText();
            boolean rewCard = jCheckBoxRewardsCard.isSelected();
            arrayList.add(new FishOrder (num, type, rewCard));
            pw = new PrintWriter ("fishPurchase.txt");
            
            for(FishOrder p : arrayList){
                pw.print(p.toString()+ "\n");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AquaticsGUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            pw.close();
        }
         
         
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AquaticsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
                                                                                     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AquaticsGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxRewardsCard;
    private javax.swing.JLabel jLabelFishQuest;
    private javax.swing.JLabel jLabelNumQuest;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelimage;
    private javax.swing.JSpinner jSpinnerNumFish;
    private javax.swing.JTextField jTextFieldTypeFish;
    // End of variables declaration//GEN-END:variables

    private void setBackground(int i, int i0, int i1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   private PrintWriter newPrintWriter(String fishOrdertxt) {
       throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  
}
